[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
name = "merger"
version = "0.1.0"
[dependencies.shared]
path = "../../modkit/builder/shared"

[dependencies.util]
path = "../../modkit/builder/wasm-tc/src/util"
