[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
name = "merger"
version = "0.1.0"

[dependencies.wasm-driver-utils]
git = "https://github.com/DiamondLovesYou/pnacl-clang-driver.git"
version = "1.0.0"
