[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
name = "merger"
version = "0.1.0"

[dependencies]
git2 = "0.6.5"

[dependencies.util]
git = "https://github.com/DiamondLovesYou/pnacl-clang-driver.git"
